### ISSUE TITLE
Provide proper source release tarballs

### ISSUE THREAD

**Issue by davexunit** [aseprite-gpl/aseprite#6]
The original Aseprite never cared about doing this because the author wanted you to buy their pre-built binaries, but for those of us that want to build from source, it's currently not easy.  The release tarballs available on GitHub are simply generated from git tags.  Since the repository has many submodules, the tarball is missing all of that code.  So, the user must do a recursive clone of the repo and checkout the tag they want to build from.  It would be great if this free software friendly fork could upload complete source releases that users can just unpack and build.

**Comment by dacap** [comment]
Hi @davexunit, actually I'm releasing proper source tarballs: https://github.com/aseprite/aseprite/releases

**Comment by davexunit** [comment]
@dacap This is a new development since 1.1.1 when I last checked.  Thanks!

This fork should do the same, my only recommendation is to a more standard gzipped tarball or xzipped tarball instead of zip.

**Comment by davexunit** [comment]
Those complete source release zips are useless because they contain a EULA in them, so they aren't free software releases.

**Comment by dacap** [comment]
> Those complete source release zips are useless because they contain a EULA in them, so they aren't free software releases.

They contain the EULA and a LICENSE file (GPLv2) and a README file that says that the the source code is distributed under GPLv2 terms. Basically the EULA is just there because the .zip is a complete clone of the repository (and I think the README is quite explicit about the licensing terms).

**Comment by Beartis** [comment]
> README file that says that the the source code is distributed under GPLv2 terms. 

This is plainly false. There is no mention of the GPL in the README file, which has not changed since your comment.

**Comment by akien-mga** [comment]
>> README file that says that the the source code is distributed under GPLv2 terms.

> This is plainly false. There is no mention of the GPL in the README file, which has not changed since your comment.

Ah? https://github.com/aseprite-gpl/aseprite/blob/03be4aa23db465219962f4c62410f628e7392545/README.md#license

**Comment by akien-mga** [comment]
And as I'm a nice guy, I even checked the official source release tarball for 1.1.7 from @dacap that were the initial topic (though kind of off-topic and borderline regarding the code-of-conduct we don't have yet but should introduce), and they do contain the same README.md file with the same mention of the code being licensed under the GPLv2.

And if you don't trust a README file, check the source headers of each code file... (In the fork, or before 03be4aa of course). Of course tarballs from 1.1.8 and later would likely differ, as Aseprite is no longer open source.

**Comment by Beartis** [comment]
It wasn't clear that dacap was referring exclusively to past releases.

**Comment by akien-mga** [comment]
Well you mentioned "which has not changed since your comment", so I wager you checked the date of the comment you replied to: 26 days ago. At what time the last release was 1.1.7, which was open source. So @dacap was not referring exclusively to past releases, but to the latest ones.

Now, the fact that newer releases changed license is out of the scope of this issue.

**Comment by akien-mga** [comment]
I uploaded a "proper" source tarball for 1.1.7 (the same one as @dacap's, with the sole modification that it now has a root folder named `aseprite-1.1.7` so it won't extract its files directly in the current folder, and it's XZ-compressed which divides the size by 2).

**Comment by Beartis** [comment]
I didn't check the date of the latest open source release but rather that of the README file (27 days ago), my apologies.
